# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='쇼핑몰 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제목')),
                ('url', models.CharField(max_length=300, verbose_name='링크')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='가격')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='썸네일')),
                ('mall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mall_product', to='product.Mall', verbose_name='쇼핑몰')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_product', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '상품',
                'ordering': ['-created'],
                'verbose_name_plural': '상품',
            },
        ),
    ]
