# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160903_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='썸네일 url'),
        ),
    ]
