# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('product', '0004_product_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='즐겨찾기')),
                ('is_archived', models.BooleanField(default=False, verbose_name='보관하기')),
            ],
            options={
                'verbose_name': '상품 주인',
                'verbose_name_plural': '상품 주인',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='personalproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_product', to='product.Product', verbose_name='제품'),
        ),
        migrations.AddField(
            model_name='personalproduct',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='personalproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_product', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
