# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20160907_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalproduct',
            options={'ordering': ['-created'], 'verbose_name': '개인별 상품', 'verbose_name_plural': '개인별 상품'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated'], 'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
    ]
