# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20160914_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_src',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='썸네일 소스'),
        ),
    ]
