# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_auto_20160914_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='리스트 이름')),
                ('product', models.ManyToManyField(blank=True, to='product.PersonalProduct', verbose_name='리스트 제품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_list', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mall',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mall',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
