# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 07:18
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to='image/avatar/%Y/%m/%d', verbose_name='아바타'),
        ),
    ]
